config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :teams, only: %i[index show]

  resources :users do
    resources :entries, only: %i[create edit new update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id          :bigint           not null, primary key
#  date        :datetime
#  impediments :text
#  today       :text
#  yesterday   :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_entries_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Entry < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true

  def self.for_date(date)
    where(date: date)
  end
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Team < ApplicationRecord
  has_many :users
  has_many :entries, through: :users
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean          default(FALSE)
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  team_id                :bigint
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_team_id               (team_id)
#
# Foreign Keys
#
#  fk_rails_...  (team_id => teams.id)
#
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :team, optional: true
  has_many :entries, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  private

  def date
    if params[:date]
      Date.parse(params[:date])
    else
      Date.today
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
    @entry = user.entries.new
    @date = date
  end

  def edit
    @entry = entry.find(params[id])
    @date = date
  end

  def create
    @entry = user.entries.build(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to user_entries_path(@user), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:date, :yesterday, :today, :impediments, :user_id)
  end

  def user
    User.find(params[:user_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @entries = team.entries.for_date(date)
    @date = date
    @users_not_reporting = users_not_reporting
  end

  private

  def team
    @team ||= Team.includes(users: :entries).find(params[:id])
  end

  def users_not_reporting
    reporting_user_ids = @entries.pluck(:user_id)
    @team.users.where.not(id: reporting_user_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url_for(email)
    gravatar_id = Digest::MD5.hexdigest(email)
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end

  def display_name_for(user)
    if user.full_name == " "
      user.email
    else
      user.full_name
    end
  end
end

app/views/entries/_form.slim
= form_with model: @entry, url: user_entries_path, local: true do |f|
  = f.hidden_field :date, value: @date
  .form-group
    = f.label :yesterday
    = f.text_field :yesterday, class: "form-control"
  .form-group
    = f.label :today
    = f.text_field :today, class: "form-control"
  .form-group
    = f.label :impediments
    = f.text_field :impediments, class: "form-control"
  = f.submit class: "btn btn-primary"

app/views/entries/edit.slim
= render partial: "form"

app/views/entries/new.slim
= render partial: "form"

app/views/home/index.slim
table
  tr
    td home!

app/views/layouts/application.slim
doctype html
html lang="en"
  head
    title Scruminator
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"

  body
    = render partial: "shared/navbar"
    - if notice
      p.alert.alert-success= notice
    - if alert
      p.alert.alert-danger= alert

    main.container-fluid
      = yield
    = render partial: "shared/footer"

app/views/shared/_footer.slim
footer.container-fluid.mt-5.p-3.text-center.bg-dark.text-light Made with ❤️

app/views/shared/_navbar.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  a.navbar-brand href="#" Scruminator
  - if current_user
    button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon

    div.collapse.navbar-collapse#navbarSupportedContent
      ul.navbar-nav.mr-auto
        li.nav-item.active
          a.nav-link href="#"
            | Home
            span.sr-only (current)
        li.nav-item.active
        - if current_user.admin
          li.nav-item.dropdown
            a.nav-link.dropdown-toggle href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" Admin
            div.dropdown-menu aria-labelledby="navbarDropdown"
              = link_to "Teams", teams_path, class: "dropdown-item"
      ul.navbar-nav.ml-auto
        li.nav-item.dropdown
          a.nav-link.dropdown-toggle href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
            = display_name_for(current_user)
            = image_tag avatar_url_for(current_user.email), class: "user-avatar ml-2"
          div.dropdown-menu aria-labelledby="userDropdown"
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              = fa_icon "sign-out", class: "mr-2"
              | Sign out